stages:
- stage: BuildDeploy
  jobs:
  - job: BuildDeploy
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        # Install AWS CLI
        python -m pip install --upgrade pip==9.0.3 setuptools wheel
        pip install awscli --user
        aws --version

        # Install Skaffold
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold
        sudo mv skaffold /usr/local/bin
        skaffold version

        # Install aws-iam-authenticator
        curl -Lo aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator
        chmod +x aws-iam-authenticator
        sudo mv aws-iam-authenticator /usr/local/bin
        aws-iam-authenticator version

        # Install kubectl
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin
        kubectl --help
      displayName: 'Install tools'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-staging'
        regionName: 'eu-west-1'
        scriptType: 'inline'
        inlineScript: |
          eval $(/home/vsts/.local/bin/aws ecr get-login --no-include-email)
      displayName: 'Login to ECR'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-staging'
        regionName: 'eu-west-1'
        scriptType: 'inline'
        inlineScript: |
          aws eks update-kubeconfig --name ferocious-rainbow-1573565336
      displayName: 'Set kubeconfig'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-staging'
        regionName: 'eu-west-1'
        scriptType: 'inline'
        inlineScript: |
          #skaffold build --file-output=image_tags.json --default-repo=935004547008.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo
          #cat image_tags.json
          skaffold deploy --build-artifacts=image_tags_static.json --default-repo=935004547008.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo
      displayName: 'Run skaffold'
- stage: Test
  jobs:
  - job: LoadTest
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        docker pull loadimpact/k6:0.25.1
        ls -lh $BUILD_SOURCES_DIRECTORY
        ls -lh $BUILD_SOURCES_DIRECTORY/loadimpact/microservices-demo/
        docker run -i -e K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN -v $BUILD_SOURCES_DIRECTORY:/ci/ loadimpact/k6:0.25.1 run -q -e PROJECT_ID=$LI_PROJECT_ID /ci/loadimpact/microservices-demo/tests/loadtests/main.js
      env:
        BUILD_SOURCES_DIRECTORY: $(Build.SourcesDirectory)
