stages:
- stage: Pipeline
  jobs:
  - job: Pipeline
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        # Install AWS CLI
        python -m pip install --upgrade pip==9.0.3 setuptools wheel
        pip install awscli --user

        # Install Skaffold
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
        chmod +x skaffold
        sudo mv skaffold /usr/local/bin

        # Install kubectl
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
      displayName: 'Install tools'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-staging'
        regionName: 'eu-west-1'
        scriptType: 'inline'
        inlineScript: |
          eval $(/home/vsts/.local/bin/aws ecr get-login --no-include-email)
      displayName: 'Login to ECR'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-staging'
        regionName: 'eu-west-1'
        scriptType: 'inline'
        inlineScript: |
          aws eks update-kubeconfig --name ferocious-rainbow-1573565336
      displayName: 'Set kubeconfig'
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-staging'
        regionName: 'eu-west-1'
        scriptType: 'inline'
        inlineScript: |
        skaffold run --default-repo=935004547008.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo
      displayName: 'Run skaffold'
